# Generated by Django 5.2.4 on 2025-07-24 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trade",
            old_name="excnahge",
            new_name="exchange",
        ),
    ]
