# Generated by Django 5.2.6 on 2025-10-29 15:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_auditlog_exchangecredential_transferrequest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="futurestrade",
            name="external_id",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="spottrade",
            name="external_id",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name="futurestrade",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_id__isnull", True), _negated=True),
                fields=("user", "exchange", "external_id"),
                name="uniq_user_exchange_external_futures",
            ),
        ),
        migrations.AddConstraint(
            model_name="spottrade",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_id__isnull", True), _negated=True),
                fields=("user", "exchange", "external_id"),
                name="uniq_user_exchange_external_spot",
            ),
        ),
    ]
