name: tests
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend   # manage.py lives here
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -r requirements.txt

      - name: Run checks & tests
        env:
          # CI-safe values – do NOT put real secrets here
          SECRET_KEY: "ci-secret-not-for-prod"
          DEBUG: "False"
          FIELD_ENCRYPTION_KEY: ${{ secrets.FIELD_ENCRYPTION_KEY }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: |
          python manage.py check
          pytest -q
